2019-07-08 17:55:44,929 - INFO - regsnp_intron.feature_calculator - Checking input file format.
Traceback (most recent call last):
  File "/usr/local/bin/regsnp_intron", line 4, in <module>
    __import__('pkg_resources').run_script('regsnp-intron==0.1.6', 'regsnp_intron')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/regsnp_intron-0.1.6-py2.7.egg/EGG-INFO/scripts/regsnp_intron", line 65, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/regsnp_intron-0.1.6-py2.7.egg/EGG-INFO/scripts/regsnp_intron", line 51, in main
    
  File "build/bdist.linux-x86_64/egg/regsnp_intron/feature_calculator.py", line 45, in calculate_feature
  File "build/bdist.linux-x86_64/egg/regsnp_intron/utils/snp.py", line 30, in is_valid
  File "pysam/libcfaidx.pyx", line 123, in pysam.libcfaidx.FastaFile.__cinit__
  File "pysam/libcfaidx.pyx", line 155, in pysam.libcfaidx.FastaFile._open
IOError: file `/var/www/Muri/data/db/hg19/hg19.fa` not found
